In [1]:
# IMPORTING LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Load Dataset,   *read_csv:load csv file into dataframe
df=pd.read_csv("customer_shopping_behavior.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
# DATA INSPECTION

print("First 5 rows:")
print(df.head())

print("\nLast 5 rows:")
print(df.tail())

print("\nDataset Shape:")
print(df.shape)           # show dataframe dimension(to display total rows,coln)

print("\nColumn Names:")
print(df.columns.tolist())

First 5 rows:
   Customer ID  Age  Gender Item Purchased     Category  \
0         2701   22  Female        T-shirt     Clothing
1          521   51    Male     Sunglasses  Accessories
2         3157   18  Female          Shirt     Clothing
3         1687   22    Male         Gloves  Accessories
4         2929   40  Female        Jewelry  Accessories

   Purchase Amount (USD)        Location Size   Color  Season  Review Rating  \
0                   68.0      California   XL   Olive  Winter            3.2
1                   84.0  South Carolina    M   White  Spring            3.9
2                   50.0         Montana    M   Black  Winter            3.1
3                   75.0        Illinois    L     Red    Fall            4.2
4                   80.0         Alabama    L  Yellow  Spring            3.6

  Subscription Status   Shipping Type Discount Applied  Previous Purchases  \
0                  No        Standard               No                36.0
1                 Yes   Free Shipping              Yes                20.0
2                  No  2-Day Shipping               No                18.0
3                  No    Store Pickup               No                25.0
4                  No    Store Pickup               No                17.0

  Payment Method Frequency of Purchases
0           Cash                 Weekly
1     Debit Card              Quarterly
2           Cash                Monthly
3           Cash               Annually
4    Credit Card                 Weekly

Last 5 rows:
      Customer ID  Age  Gender Item Purchased     Category  \
5045          913   24    Male         Hoodie     Clothing
5046         3466   19  Female       Backpack  Accessories
5047         3572   70  Female          Skirt     Clothing
5048         3195   43  Female       Sneakers     Footwear
5049         1832   62    Male         Blouse     Clothing

      Purchase Amount (USD)      Location Size  Color  Season  Review Rating  \
5045                   56.0      Arkansas    M  Green  Winter            3.4
5046                   53.0          Iowa    M   Gold  Spring            3.4
5047                   27.0  North Dakota    M  White  Summer            3.2
5048                   52.0      Maryland    L   Gold  Summer            4.6
5049                   71.0         Maine    M   Cyan  Summer            3.3

     Subscription Status  Shipping Type Discount Applied  Previous Purchases  \
5045                 Yes   Next Day Air              Yes                32.0
5046                  No       Standard               No                31.0
5047                  No       Standard               No                15.0
5048                  No       Standard               No                10.0
5049                  No  Free Shipping               No                 5.0

     Payment Method Frequency of Purchases
5045  Bank Transfer                Monthly
5046     Debit Card                 Weekly
5047  Bank Transfer         Every 3 Months
5048    Credit Card              Bi-Weekly
5049  Bank Transfer         Every 3 Months

Dataset Shape:
(5050, 17)

Column Names:
['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']

In [4]:
# display specific rows
df.head(2)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly

In [5]:
#display total no. of records/rows
len(df)

5050

In [6]:
#  DATA INFORMATION: display coln info (coln name,no. of coln, datatype) and null count.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   str
 3   Item Purchased          5050 non-null   str
 4   Category                5050 non-null   str
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   str
 7   Size                    4680 non-null   str
 8   Color                   5050 non-null   str
 9   Season                  5050 non-null   str
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   str
 12  Shipping Type           5050 non-null   str
 13  Discount Applied        5050 non-null   str
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   str
 16  Frequency of Purchases  5050 non-null   str
dtypes: float64(3), int64(2), str(12)
memory usage: 670.8 KB

In [7]:
#statistical summary of numerical columns, including:Count ,Mean (average),Std deviation,Min value,Quartiles (25%, 50%, 75%)
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [8]:
# check Missing Values: count of null/missing values in each coln
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [9]:
#show all purchased item
df["Item Purchased"]

0          T-shirt
1       Sunglasses
2            Shirt
3           Gloves
4          Jewelry
           ...
5045        Hoodie
5046      Backpack
5047         Skirt
5048      Sneakers
5049        Blouse
Name: Item Purchased, Length: 5050, dtype: str

In [10]:
#It returns all unique values from the "Item Purchased" column.
df["Item Purchased"].unique()

<StringArray>
[   'T-shirt', 'Sunglasses',      'Shirt',     'Gloves',    'Jewelry',
     'Shorts',        'Hat',    'Handbag',      'Shoes',       'Coat',
     'Laptop',     'Hoodie',      'Phone',     'Jacket',      'Pants',
   'Backpack',      'Socks',      'Jeans',        'Bag',       'Belt',
      'Watch', 'Headphones',     'Blouse',    'Sandals',      'Skirt',
    'Sweater',      'Scarf',   'Sneakers',      'Boots',      'Dress']
Length: 30, dtype: str

In [11]:
df["Category"].unique()

<StringArray>
['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear']
Length: 5, dtype: str

In [12]:
#groups your data by Category and then shows the unique items purchased within each category.
df.groupby("Category")["Item Purchased"].unique()

Category
Accessories    [Sunglasses, Gloves, Jewelry, Hat, Handbag, Ph...
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone,...
Electronics    [Laptop, Phone, Watch, Bag, Shoes, Shirt, Head...
Footwear                       [Shoes, Sandals, Sneakers, Boots]
Outerwear                                         [Coat, Jacket]
Name: Item Purchased, dtype: object

In [13]:
# above o/p can't see all values ...
pd.set_option("display.max_colwidth",None)  #to display the full content of each column

#display.max_colwidth → controls maximum width of column content, None → means no limit (show full text)

In [14]:
df.groupby("Category")["Item Purchased"].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [15]:
#wrong mapping eg: Shoes in Electronics, Laptop in Accessories / Clothing / Electronics
#stored in key-value paired.
category_map = {
    # Clothing
    "T-shirt": "Clothing",
    "Shirt": "Clothing",
    "Shorts": "Clothing",
    "Hoodie": "Clothing",
    "Pants": "Clothing",
    "Socks": "Clothing",
    "Jeans": "Clothing",
    "Blouse": "Clothing",
    "Skirt": "Clothing",
    "Sweater": "Clothing",
    "Dress": "Clothing",

    # Accessories
    "Sunglasses": "Accessories",
    "Gloves": "Accessories",
    "Jewelry": "Accessories",
    "Hat": "Accessories",
    "Handbag": "Accessories",
    "Backpack": "Accessories",
    "Belt": "Accessories",
    "Bag": "Accessories",
    "Scarf": "Accessories",
    "Watch": "Accessories",

    # Electronics
    "Laptop": "Electronics",
    "Phone": "Electronics",
    "Headphones": "Electronics",

    # Footwear
    "Shoes": "Footwear",
    "Sandals": "Footwear",
    "Sneakers": "Footwear",
    "Boots": "Footwear",

    # Outerwear
    "Coat": "Outerwear",
    "Jacket": "Outerwear"
}

# Apply mapping (replace values using a dictionary)
df["Category"] = df["Item Purchased"].map(category_map)

In [16]:
#to check again it was correct map or not
df.groupby("Category")["Item Purchased"].unique()

Category
Accessories          [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Watch, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                             [Laptop, Phone, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: Item Purchased, dtype: object

In [17]:
df.isnull().sum() #count of null value

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

# Treating  null value in size coln

In [18]:
df["Size"].unique()

<StringArray>
['XL', 'M', 'L', 'S', nan]
Length: 5, dtype: str

In [19]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [20]:
# from above table we know the size are given according to item puchased. so group by
df.groupby("Item Purchased")["Size"].unique()

Item Purchased
Backpack           [M, S, L, XL]
Bag           [M, L, nan, XL, S]
Belt               [M, S, XL, L]
Blouse             [M, L, S, XL]
Boots              [L, M, XL, S]
Coat               [XL, M, S, L]
Dress              [XL, M, L, S]
Gloves             [L, M, S, XL]
Handbag            [S, XL, M, L]
Hat                [M, L, S, XL]
Headphones    [S, M, nan, L, XL]
Hoodie             [M, L, S, XL]
Jacket             [L, S, M, XL]
Jeans              [L, M, XL, S]
Jewelry            [L, XL, M, S]
Laptop        [nan, M, S, XL, L]
Pants              [L, M, XL, S]
Phone         [nan, L, S, M, XL]
Sandals            [M, S, L, XL]
Scarf              [M, L, S, XL]
Shirt         [M, XL, L, S, nan]
Shoes         [M, L, nan, XL, S]
Shorts             [S, M, L, XL]
Skirt              [S, L, M, XL]
Sneakers           [S, M, L, XL]
Socks              [M, XL, L, S]
Sunglasses         [M, L, S, XL]
Sweater            [M, S, L, XL]
T-shirt            [XL, M, S, L]
Watch         [nan, M, L, XL, S]
Name: Size, dtype: object

In [21]:
df.groupby("Category")["Size"].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [22]:
#for filling coln: In electronicis not have size so relace it as Not Applicable.
#Treating null values or relacing all values.
df.loc[df["Category"]=="Electronics","Size"]="Not Applicable"

In [23]:
#to see changes
df.groupby("Category")["Size"].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics      [Not Applicable]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [24]:
#In Accessories not have size so relace it as Free Size.
df.loc[df["Category"]=="Accessories","Size"]="Free Size" 

# In footwear category size are not in L,M,S they are in number so replace it as Not Available.
df.loc[df["Category"]=="Footwear","Size"]="not available" 

#In clothing category treat null value we use mode (high number of freq: most common size)
# CODE EXPLAIN: *2 CONDn: Category = Clothing, Size is missing,
#               *Value to fill:most frequent size in Clothing
#              *0 return for if 2 similar mode then return firstly came.eg: L=100 tmis, S=100 times firstly L came then mode is L.
df.loc[
    (df["Category"] == "Clothing") & (df["Size"].isnull()),
    "Size"] = df[df["Category"] == "Clothing"]["Size"].mode()[0]

# ONLY want to fill missing values in  footwear category:

df.loc[
    (df["Category"] == "Accessories") & (df["Size"].isnull()),
    "Size"
] = "Free Size"

In [25]:
#to see changes
df.groupby("Category")["Size"].unique()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [not available]
Outerwear         [XL, L, S, M]
Name: Size, dtype: object

In [26]:
# to check treated null value for size coln
df.isnull().sum() #count of null value

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

# Treating Review Rating null values

In [27]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [28]:
#Mean of Review Rating(avg value)
df["Review Rating"].mean()

np.float64(3.668195100022477)

In [29]:
#median of Review Rating (middle values)
df["Review Rating"].median()

np.float64(3.7)

In [30]:
#mode of Review Rating(most freq value)
df["Review Rating"].mode()

0    4.0
Name: Review Rating, dtype: float64

In [31]:
# review rating given according to item purchased so group by
#so we see each item purchased AVG rating
df.groupby("Item Purchased")["Review Rating"].mean()

Item Purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: Review Rating, dtype: float64

In [32]:
#filling null values of review rating with the mean of each item purchased.

#explain code:* Replaces only NaN values (in review rating coln fillna means null value)
#             *in that where each row gets the mean review rating of its item purchased. 

df["Review Rating"]=df["Review Rating"].fillna(df.groupby("Item Purchased")["Review Rating"].transform("mean"))

In [33]:
# to check review rating null are handled
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [34]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,Free Size,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,Free Size,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,Free Size,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

# Treating Previous Purchases null values

In [35]:
# Previously Purchases so we treat null value as zero(0)
df["Previous Purchases"]=df["Previous Purchases"].fillna(0)

In [36]:
#to check null are handled
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                        0
Color                       0
Season                      0
Review Rating               0
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases          0
Payment Method              0
Frequency of Purchases      0
dtype: int64

# Treating Purchase Amount (USD) null values

In [37]:
# calculates the average purchase amount (USD) for each item.
df.groupby("Item Purchased")["Purchase Amount (USD)"].mean()

Item Purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: Purchase Amount (USD), dtype: float64

In [38]:
#filling null values of purchase amount with the mean of each item purchased.

df["Purchase Amount (USD)"]=df["Purchase Amount (USD)"].fillna(df.groupby("Item Purchased")["Purchase Amount (USD)"]
                                               .transform("mean"))

In [39]:
# To check count of null
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

# Check Duplicate Records

In [40]:
#TO check count of duplicated
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 50

In [41]:
# To show duplicated record
df[df.duplicated()]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.300000,No,Free Shipping,No,19.0,Cash,Monthly
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,Free Size,Charcoal,Winter,3.100000,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.500000,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,not available,Maroon,Winter,2.900000,No,Standard,No,35.0,Credit Card,Fortnightly
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,not available,Orange,Winter,2.800000,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly
1797,3639,40,Female,Backpack,Accessories,20.0,Kansas,Free Size,Olive,Spring,4.600000,No,Express,No,50.0,PayPal,Bi-Weekly
1870,3456,49,Female,T-shirt,Clothing,89.0,Ohio,M,Orange,Fall,4.700000,No,Standard,No,13.0,Venmo,Annually
2033,1812,42,Male,Belt,Accessories,77.0,Wisconsin,Free Size,Blue,Summer,3.600000,No,Standard,No,33.0,Bank Transfer,Annually
2113,3040,59,Female,Blouse,Clothing,48.0,Alabama,L,Blue,Spring,3.200000,No,Next Day Air,No,31.0,PayPal,Bi-Weekly
2226,1371,27,Male,Scarf,Accessories,67.0,Montana,Free Size,Peach,Summer,3.702564,No,2-Day Shipping,Yes,41.0,Bank Transfer,Every 3 Months
2358,2977,30,Female,Coat,Outerwear,97.0,Nebraska,M,Silver,Summer,2.800000,No,Express,No,28.0,Cash,Fortnightly
2447,2678,45,Female,Shorts,Clothing,43.0,Connecticut,L,Olive,Spring,3.800000,No,Next Day Air,No,6.0,PayPal,Every 3 Months
2630,992,20,Male,Shorts,Clothing,97.0,Wisconsin,XL,White,Spring,2.700000,Yes,Standard,Yes,40.0,Bank Transfer,Bi-Weekly
2642,1566,58,Male,Sunglasses,Accessories,93.0,Idaho,Free Size,Peach,Fall,4.200000,No,Free Shipping,Yes,48.0,PayPal,Annually
2739,2227,22,Male,Shirt,Clothing,72.0,Missouri,L,Blue,Spring,4.800000,No,Store Pickup,No,28.0,Cash,Annually
2740,3487,51,Female,Shorts,Clothing,89.0,North Carolina,L,Charcoal,Winter,4.900000,No,Standard,No,6.0,PayPal,Weekly
2800,2069,70,Male,Jewelry,Accessories,81.0,Vermont,Free Size,Black,Summer,3.900000,No,Store Pickup,No,44.0,Venmo,Monthly
2905,2158,41,Male,Handbag,Accessories,68.0,Mississippi,Free Size,Turquoise,Winter,4.000000,No,Next Day Air,No,41.0,Venmo,Fortnightly
2922,3334,55,Female,Jeans,Clothing,35.0,Minnesota,M,Violet,Spring,4.200000,No,Express,No,3.0,PayPal,Monthly
3036,258,20,Male,Handbag,Accessories,53.0,West Virginia,Free Size,Red,Summer,4.500000,Yes,Express,Yes,5.0,Credit Card,Quarterly
3065,3887,37,Female,Jewelry,Accessories,92.0,Iowa,Free Size,Brown,Summer,3.900000,No,Express,No,40.0,Debit Card,Quarterly
3185,1609,26,Male,Sandals,Footwear,58.0,Nebraska,not available,Cyan,Fall,4.600000,No,Next Day Air,Yes,12.0,Bank Transfer,Bi-Weekly
3357,3091,29,Female,Shirt,Clothing,36.0,Texas,M,Peach,Summer,4.900000,No,Store Pickup,No,15.0,Bank Transfer,Quarterly
3390,603,37,Male,Shoes,Footwear,58.0,Oregon,not available,Lavender,Summer,4.200000,Yes,Next Day Air,Yes,10.0,Cash,Every 3 Months
3538,1698,36,Male,Shirt,Clothing,87.0,South Carolina,L,Lavender,Fall,3.500000,No,Next Day Air,No,48.0,Credit Card,Every 3 Months
3683,1209,20,Male,Boots,Footwear,100.0,Wisconsin,not available,Red,Winter,3.813194,No,2-Day Shipping,Yes,8.0,Debit Card,Annually
3698,172,29,Male,Shorts,Clothing,35.0,Virginia,M,Blue,Summer,3.600000,Yes,Store Pickup,Yes,4.0,Credit Card,Weekly
3742,323,41,Male,Belt,Accessories,95.0,Tennessee,Free Size,Cyan,Winter,3.000000,Yes,Standard,Yes,47.0,Credit Card,Monthly
3810,2429,65,Male,T-shirt,Clothing,38.0,Idaho,M,Violet,Spring,4.400000,No,Next Day Air,No,34.0,Debit Card,Annually
3843,615,68,Male,Jewelry,Accessories,85.0,Idaho,Free Size,Lavender,Winter,4.000000,Yes,Standard,Yes,21.0,Credit Card,Bi-Weekly
3961,2558,70,Male,Shorts,Clothing,23.0,Oklahoma,L,Cyan,Spring,3.900000,No,Standard,No,17.0,PayPal,Fortnightly
3987,3507,18,Female,Shirt,Clothing,57.0,Illinois,L,Olive,Winter,3.700000,No,2-Day Shipping,No,12.0,Cash,Fortnightly
4050,3287,45,Female,Jacket,Outerwear,67.0,Illinois,L,Pink,Winter,5.000000,No,Express,No,4.0,Venmo,Fortnightly
4059,227,29,Male,Shoes,Footwear,74.0,Texas,not available,Violet,Spring,3.300000,Yes,Free Shipping,Yes,5.0,PayPal,Monthly
4131,2642,25,Male,Sunglasses,Accessories,60.0,Vermont,Free Size,Olive,Winter,2.700000,No,Next Day Air,No,20.0,Bank Transfer,Every 3 Months
4183,1523,38,Male,Shorts,Clothing,72.0,Tennessee,L,Yellow,Spring,4.800000,No,Free Shipping,Yes,5.0,Debit Card,Monthly
4330,3716,63,Female,Sunglasses,Accessories,34.0,Nebraska,Free Size,Orange,Fall,3.400000,No,Free Shipping,No,2.0,Bank Transfer,Monthly
4390,3846,58,Female,Sweater,Clothing,52.0,California,M,Green,Winter,4.900000,No,Standard,No,46.0,Venmo,Annually
4445,3644,53,Female,Scarf,Accessories,96.0,Tennessee,Free Size,Magenta,Fall,3.200000,No,Standard,No,47.0,Debit Card,Annually
4468,473,20,Male,Jeans,Clothing,39.0,Georgia,L,Gray,Winter,3.900000,Yes,Free Shipping,Yes,3.0,Bank Transfer,Quarterly
4513,1317,28,Male,Belt,Accessories,32.0,Arkansas,Free Size,Lavender,Spring,4.600000,No,Standard,Yes,14.0,Debit Card,Bi-Weekly
4558,3339,29,Female,Skirt,Clothing,94.0,Minnesota,L,White,Winter,2.900000,No,2-Day Shipping,No,46.0,Credit Card,Monthly
4595,3577,29,Female,Boots,Footwear,24.0,Maine,not available,Yellow,Spring,3.000000,No,Express,No,12.0,Venmo,Bi-Weekly
4664,2689,53,Female,Handbag,Accessories,63.0,West Virginia,Free Size,Turquoise,Spring,2.900000,No,2-Day Shipping,No,18.0,Credit Card,Every 3 Months
4717,2800,23,Female,T-shirt,Clothing,89.0,Maine,L,Pink,Spring,3.900000,No,Free Shipping,No,9.0,Bank Transfer,Every 3 Months
4735,2182,22,Male,Handbag,Accessories,63.0,Hawaii,Free Size,Black,Fall,3.200000,No,Free Shipping,No,32.0,Bank Transfer,Bi-Weekly
4841,2622,48,Male,Shoes,Footwear,46.0,Maine,not available,Beige,Winter,3.000000,No,Express,No,21.0,Bank Transfer,Annually
4887,3875,70,Female,Sweater,Clothing,54.0,Nevada,XL,Beige,Summer,3.900000,No,2-Day Shipping,No,33.0,Credit Card,Bi-Weekly
4901,1060,22,Male,Jacket,Outerwear,34.0,North Carolina,M,Beige,Winter,2.500000,No,Standard,Yes,25.0,Debit Card,Monthly
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.000000,No,Store Pickup,No,33.0,Credit Card,Monthly

In [42]:
# To check particular record how many times duplicated
df[df["Customer ID"]==3439]

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
3410,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.0,No,Store Pickup,No,33.0,Credit Card,Monthly
5037,3439,26,Female,Shirt,Clothing,71.0,Kentucky,M,Violet,Fall,3.0,No,Store Pickup,No,33.0,Credit Card,Monthly

In [43]:
#To see no. of records
len(df)

5050

In [44]:
#Delete duplicated records
df=df.drop_duplicates(subset=["Customer ID"],keep="first")   # keep=1st means keep 1st record onward record drop

In [45]:
#to check duplicated record
df.duplicated().sum()

np.int64(0)

In [46]:
#To show each coln count
df.count()

Customer ID               5000
Age                       5000
Gender                    5000
Item Purchased            5000
Category                  5000
Purchase Amount (USD)     5000
Location                  5000
Size                      5000
Color                     5000
Season                    5000
Review Rating             5000
Subscription Status       5000
Shipping Type             5000
Discount Applied          5000
Previous Purchases        5000
Payment Method            5000
Frequency of Purchases    5000
dtype: int64

# Renaming the Headers

In [47]:
#It returns the list of all columns names 
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='str')

In [48]:
df.columns=df.columns.str.replace(" ","_")   #all column in that str replace blank space as underscore.

In [49]:
#TO check
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount_(USD)', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Previous_Purchases', 'Payment_Method',
       'Frequency_of_Purchases'],
      dtype='str')

In [50]:
# to rename Purchase_Amount_(USD) as Purchase_Amount
df=df.rename(columns={"Purchase_Amount_(USD)":"Purchase_Amount"})   # in form dic={key:value}

In [51]:
#TO check
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Previous_Purchases', 'Payment_Method',
       'Frequency_of_Purchases'],
      dtype='str')

In [52]:
# Replace "Every 3 Months" with "Quarterly"
# Replace "Fortnightly" with "Bi-Weekly"

df["Frequency_of_Purchases"] = df["Frequency_of_Purchases"].replace({
    "Every 3 Months": "Quarterly",
    "Fortnightly": "Bi-Weekly"
})

In [53]:
# ==============================
#  FINAL DATA CHECK
# ==============================

print("Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Shape: (5000, 17)

Missing Values:
Customer_ID               0
Age                       0
Gender                    0
Item_Purchased            0
Category                  0
Purchase_Amount           0
Location                  0
Size                      0
Color                     0
Season                    0
Review_Rating             0
Subscription_Status       0
Shipping_Type             0
Discount_Applied          0
Previous_Purchases        0
Payment_Method            0
Frequency_of_Purchases    0
dtype: int64

Duplicate Rows:
0

Data Types:
Customer_ID                 int64
Age                         int64
Gender                        str
Item_Purchased                str
Category                      str
Purchase_Amount           float64
Location                      str
Size                          str
Color                         str
Season                        str
Review_Rating             float64
Subscription_Status           str
Shipping_Type                 str
Discount_Applied              str
Previous_Purchases        float64
Payment_Method                str
Frequency_of_Purchases        str
dtype: object

In [54]:
df.to_csv(
    "customer_shopping_clean_data.csv",
    index=False
)